[package]
name = "sdfu"
version = "0.0.1"
authors = ["Gray Olson <gray@grayolson.com>"]
description = "signed distance field utilities"
license = "MIT+Apache-2.0"
repository = "https://github.com/termhn/sdfu"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
